# Generated by Django 5.2.10 on 2026-02-25 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otryad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IshchiGuruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('otryad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guruhlar', to='my_app.otryad')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=20)),
                ('tabel_raqami', models.CharField(max_length=50)),
                ('is_boss', models.BooleanField(default=False)),
                ('viloyat', models.CharField(blank=True, max_length=100, null=True)),
                ('shahar_tuman', models.CharField(blank=True, max_length=100, null=True)),
                ('mahalla', models.CharField(blank=True, max_length=100, null=True)),
                ('kocha', models.CharField(blank=True, max_length=100, null=True)),
                ('uy_raqami', models.CharField(blank=True, max_length=20, null=True)),
                ('razryad', models.CharField(blank=True, max_length=10, null=True)),
                ('oklad', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('activation_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('guruh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.ishchiguruh')),
                ('otryad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.otryad')),
            ],
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='my_app.userprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='chat_videos/')),
                ('voice', models.FileField(blank=True, null=True, upload_to='chat_voices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.ishchiguruh')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('oklad', models.FloatField(default=0)),
                ('norma_soati', models.FloatField(default=0)),
                ('ishlagan_soati', models.FloatField(default=0)),
                ('tungi_soati', models.FloatField(default=0)),
                ('bayram_soati', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.userprofile')),
            ],
        ),
    ]
