# Generated by Django 5.2.10 on 2026-02-28 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_userprofile_is_working_userprofile_work_start_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='longitude',
            new_name='lng',
        ),
    ]
