# Generated by Django 5.2.10 on 2026-02-28 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_rename_latitude_userprofile_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='lng',
            new_name='longitude',
        ),
    ]
