# Generated by Django 5.2.10 on 2026-02-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_rename_lat_userprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='distance_km',
            field=models.FloatField(default=0.0),
        ),
    ]
